default_stages: [pre-push]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0  # Atualizei para uma versão mais recente
    hooks:
      - id: check-yaml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff-check
        entry: poetry run ruff check . --fix
        language: system
        types: [python]
      - id: ruff-format
        name: ruff-format
        entry: poetry run ruff format .
        language: system
        types: [python]
      - id: bandit
        name: bandit
        entry: poetry run bandit -r .
        language: system
        types: [python]
      - id: mypy
        name: mypy
        entry: poetry run mypy app/
        language: system
        types: [python]