# TODO: TXS ROUTES
# TODO: /TXS/:STR/:PAGE TESTS
# TODO: RETURN 200 -> 20 TXS
# TODO: RETURN 404: -> TRANSAÇÕES NÃO ENCONTRADAS
# TODO: RETURN 500 -> ERRO AO PEGAR AS TXS
# TODO: RETURN 401 -> CHAVE DE API AUSENTE
# TODO: RETURN 401 -> CHAVE DE API INVÁLIDA
# TODO: RETURN 500 -> ERRO DE CONFIGURAÇÃO DA CHAVE DE API

# TODO: /LAST_TXS TESTS
# TODO: RETURN 200 -> 10 TXS
# TODO: RETURN 500 -> FALHA AO RETORNAS AS TXS
# TODO: RETURN 401 -> CHAVE DE API AUSENTE
# TODO: RETURN 401 -> CHAVE DE API INVÁLIDA
# TODO: RETURN 500 -> ERRO DE CONFIGURAÇÃO DA CHAVE DE API
