"""empty message

Revision ID: 300586ff8203
Revises: 192b2215e905
Create Date: 2025-06-14 19:45:44.304961

"""
from alembic import op
import sqlalchemy as sa
from dotenv import load_dotenv
import os
from app.data.models import Transaction, Wallet

# revision identifiers, used by Alembic.
revision = '300586ff8203'
down_revision = '192b2215e905'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('percent_from_wallet', sa.Float(), default=0))
    # ### end Alembic commands ###
    load_dotenv()
    engine = sa.create_engine(os.environ["DATABASE_URI"])
    with engine.connect() as conn:
        txs = conn.scalars(sa.select(Transaction)).all()
        for tx in txs:
            tx.percent_from_wallet = float(tx.balance_usd / tx.wallet.balance_usd)
        conn.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('percent_from_wallet')

    # ### end Alembic commands ###
