# TODO: WALLETS ROUTES
# TODO: WALLETS/ALL TESTS
# TODO: RETURN 200 -> WALLETS
# TODO: RETURN 404 -> CARTEIRA NÃO ENCONTRADA
# TODO: RETURN 401 -> CHAVE DE API AUSENTE
# TODO: RETURN 401 -> CHAVE DE API INVÁLIDA
# TODO: RETURN 500 -> ERRO DE CONFIGURAÇÃO DA CHAVE DE API

# TODO: WALLETS/:ADDRESS TESTS
# TODO: GET
# TODO: RETURN 200 -> WALLET
# TODO: RETURN 404 -> CARTEIRA NÃO ENCONTRADA
# TODO: RETURN 401 -> CHAVE DE API AUSENTE
# TODO: RETURN 401 -> CHAVE DE API INVÁLIDA
# TODO: RETURN 500 -> ERRO DE CONFIGURAÇÃO DA CHAVE DE API

# TODO POST
# TODO: RETURN 201 -> CARTEIRA CRIADA
# TODO: RETURN 500 -> FALHA AO OBTER DADOS DA CARTEIRA
# TODO: RETURN 500 -> FALHA AO INSERIR CARTEIRA
# TODO: RETURN 401 -> CHAVE DE API AUSENTE
# TODO: RETURN 401 -> CHAVE DE API INVÁLIDA
# TODO: RETURN 500 -> ERRO DE CONFIGURAÇÃO DA CHAVE DE API

# TODO: DELETE
# TODO: RETURN 200 -> CARTEIRA REMOVIDA
# TODO: RETURN 404 -> CARTEIRA NÃO ENCONTRADA
# TODO: RETURN 500 -> ERRO AO DELETAR CARTEIRA
# TODO: RETURN 401 -> CHAVE DE API AUSENTE
# TODO: RETURN 401 -> CHAVE DE API INVÁLIDA
# TODO: RETURN 500 -> ERRO DE CONFIGURAÇÃO DA CHAVE DE API
